name: hora_do_remedio
description: Aplicativo para lembrete de medicamentos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2

  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  cloud_firestore: 4.9.1

  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  provider: ^6.1.1

  flutter_local_notifications: ^17.2.1
  firebase_messaging: ^14.6.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo_hora_remedio.png
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"